Repository Team-BBANGZIP/BBANGZIP-iOS, pull requests merged in 2025-05, with the labels that each got.

#4 [Chore] Color, Font 세팅
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Background/BackgroundAlternative.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Background/BackgroundDimmer.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Background/BackgroundNomal.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Background/BackgroundStrong.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Background/Backgroundgray.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Background/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Component/ComponentAlternative.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Component/ComponentStrong.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Component/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/LabelAlternative.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/LabelAssistive.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/LabelDisable.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/LabelNeutral.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/LabelNomal.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Label/LabelStrong.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Primary/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Primary/PrimaryLight.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Primary/PrimaryNormal.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Primary/PrimaryStrong.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Secondary/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Secondary/SecondaryLight.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Secondary/SecondaryNormal.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Secondary/SecondaryStrong.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Static/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Static/Staticblack.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Static/Staticwhite.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todoblue1.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todoblue2.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todogreen1.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todogreen2.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todoperple2.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todopurple1.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todored1.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todored2.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todoyellow1.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Todo/Todoyellow2.colorset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-Black.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-Bold.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-ExtraBold.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-ExtraLight.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-Light.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-Medium.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-Regular.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-SemiBold.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Font/Pretendard-Thin.otf
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ContentView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Font/CustomFont.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Font/CutomColor.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/FontTestView.swift
Labels: 🖨️ chore, 🖥️ feat, 🥯 여경야경

#13 [Feature] Checkbox 컴포넌트 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Checkbox.swift
Labels: 🖥️ feat, 🥐 눈송희

#14 [Feature] TaskInputField 컴포넌트 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/TaskInputField.swift
  BBANGZIP-iOS/BBANGZIP-iOS/TaskInputField.swift
Labels: 🖥️ feat, 🥯 여경야경

#15 [Feature] BasicButtonStyle 컴포넌트 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/BbangButtonStyle.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/BbangButtonType.swift
Labels: 🖥️ feat, 🥐 눈송희

#16 [Feature] CustomToggleStyle 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/TimerToggleStyle.swift
Labels: 🖥️ feat, 🥨 유빈무빈

#17 [Feature] Taskbox 컴포넌트 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Checkbox.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Responses/TodoItem.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/TaskBox.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Utilities/DateFormatter+Extension.swift
Labels: 🖥️ feat, 🥯 여경야경

#18 [Feature] CategoryButton 구현 및 Checkbox에 컬러 적용
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/CategoryButton.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Checkbox.swift
Labels: 🖥️ feat, ⚙️ refactor, 🥐 눈송희

#21 [Network] 네트워크 레이어 구축
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Environment/InfoItem.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/DTO/Request/TestRequest.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/DTO/Response/TestResponse.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/Error/RouterError.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/Extension/Encodable+Dictionary.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/Protocol/Router.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/RouterList/TestRouter.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Service/API.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Service/Utils/Monitor.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Extension/Data+Prettier.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Utils/LoggerFactory.swift
Labels: 🖥️ feat, 🔧 setting, 🥪 샘성민스

#23 [Feature] Navigation Bar 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ContentView.swift
Labels: 🖥️ feat, 🥨 유빈무빈
