Repository Team-BBANGZIP/BBANGZIP-iOS, pull requests merged in 2025-09, with the labels that each got.

#43 [Feature] 나만의 다짐 메시지 입력 바텀시트 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/PromiseInputField.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/MyPromiseView.swift
Labels: 🖥️ feat, 🥐 눈송희

#47 [Feature] TodoView 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/messageBread.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/messageBread.imageset/messageBread.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/messageBread.imageset/messageBread@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/messageBread.imageset/messageBread@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/CalendarCellView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/DTO/Response/TimerTodoResponseDTO.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/Entities/TimerTodo.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/Entities/TodoData.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/Entities/TodoSummary.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/Enum/TodoItem.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/Repositories/TodoRepository.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/UseCases/FetchTimerTodoUseCase.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/CustomMenu.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TimerTodo/ViewModel/MockTodoRepository.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TimerTodo/ViewModel/TimerCheckedOffViewModel.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TimerTodo/ViewModel/TimerTodoViewModel.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ToDoView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/TodoViewModel.swift
Labels: 🖥️ feat, 🥨 유빈무빈

#49 [Feature] Flow 연결
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/prize.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/BreadSelectView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ContentView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/CustomMenu.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Timer/TimerView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Timer/TimerViewModel.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryAdd/View/CategoryAddView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryManage/View/CategoryListView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TimerTodo/View/CheckedOffView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ToDoView.swift
Labels: 🖥️ feat, 🥯 여경야경

#51 [Feature] TodoView 내부 로직 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/CalendarCellView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/PromiseInputField.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryManage/ViewModel/CategoryListViewModel.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ToDoView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/TodoViewModel.swift
Labels: 🖥️ feat, 🥨 유빈무빈

#59 [Feature] 바텀시트, 카테고리 관련 2차 QA 반영
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Data/Network/Router/DTO/Response/TimerTodoResponseDTO.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Domain/Entities/TodoData.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/CategoryButton.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Component/PromiseInputField.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Timer/TimerView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryAdd/View/CategoryAddView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryColor/View/PickColorView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryManage/View/CategoryListView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/CategoryManage/View/CategoryManageView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/MyPromiseView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TaskAdd/View/TaskAddView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TimerTodo/View/CheckedOffView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/ToDo/TimerTodo/ViewModel/MockTodoRepository.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/TestTimerView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ToDoView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/TodoViewModel.swift
Labels: ⚙️ refactor, 🥐 눈송희

#58 [Feature] 로그인 UI 구현
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Slogan.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Slogan.imageset/Slogan.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Slogan.imageset/Slogan@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/Slogan.imageset/Slogan@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/apple_icon.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/apple_icon.imageset/Left Icon.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/apple_icon.imageset/Left Icon@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/apple_icon.imageset/Left Icon@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/bang_background.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/bang_background.imageset/Group 1171285508.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/bang_background.imageset/Group 1171285508@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/bang_background.imageset/Group 1171285508@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/kakao_icon.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/kakao_icon.imageset/Icons.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/kakao_icon.imageset/Icons@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/kakao_icon.imageset/Icons@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/service_logo.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/service_logo.imageset/service_logo.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/service_logo.imageset/service_logo@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/service_logo.imageset/service_logo@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/team_info.imageset/Contents.json
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/team_info.imageset/team_info.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/team_info.imageset/team_info@2x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Resources/Assets.xcassets/team_info.imageset/team_info@3x.png
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ContentView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Login/LaunchView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Login/LoginView.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/Presentation/Login/LoginViewModel.swift
  BBANGZIP-iOS/BBANGZIP-iOS/Sources/ToDoView.swift
Labels: 🖥️ feat, 🥯 여경야경
